version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - estoque

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - estoque

  api-transacao:
    image: openjdk:17-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./api/target/api-0.0.1.jar:/app/api.jar
    working_dir: /app
    command:  java -jar api.jar
    depends_on:
      - kafka
    networks:
      - estoque

  consumer:
    image: openjdk:17-alpine
    ports:
      - "8081:8081"
    volumes:
      - ./servico-estoque/target/servico-estoque-1.0.jar:/app/consumer.jar
    working_dir: /app
    command: java -jar consumer.jar
    depends_on:
      - api-transacao
    networks:
      - estoque

  email-sender:
    image: openjdk:17-alpine
    ports:
      - "8082:8082"
    volumes:
      - ./servico-email/target/servico-email-1.0.jar:/app/email.jar
    working_dir: /app
    environment:
      - EMAIL_ENVIO=teste
      - EMAIL_SENHA=teste
    command: java -jar email.jar
    depends_on:
      - consumer
    networks:
      - estoque

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: estoque
      MYSQL_DATABASE: estoque
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - estoque

networks:
  estoque:
    driver: bridge